EMPRESAS = [
    {
        "nombre": "Arcor",
        "rubro": "Alimentos",
        "categoria": "alimentacion",
        "contacto": "fundacion@arcor.com",
        "telefono": "0351-489-6000",
        "web": "https://www.fundacionarcor.org",
        "notas": "Fundación Arcor: dona alimentos, útiles escolares y financia proyectos comunitarios. Tiene programas de voluntariado corporativo.",
        "provincia": "Córdoba",
        "tipo_donacion": ["alimentos", "utiles", "materiales_educativos"]
    },
    {
        "nombre": "Grupo Techint",
        "rubro": "Construcción / Siderurgia",
        "categoria": "construccion",
        "contacto": "rse@techint.com",
        "telefono": "011-4018-1000",
        "web": "https://www.techint.com",
        "notas": "A través de la Fundación Hermanos Agustín y Enrique Rocca dona materiales de construcción y financia obras de infraestructura comunitaria.",
        "provincia": "Buenos Aires",
        "tipo_donacion": ["materiales_construccion", "financiamiento_obras"]
    },
    {
        "nombre": "Loma Negra",
        "rubro": "Cementera / Construcción",
        "categoria": "construccion",
        "contacto": "sustentabilidad@lomanegra.com.ar",
        "telefono": "011-4319-3000",
        "web": "https://www.lomanegra.com",
        "notas": "Principal cementera argentina. Dona cemento y materiales para obras comunitarias. Tiene programa de RSE activo.",
        "provincia": "Buenos Aires",
        "tipo_donacion": ["cemento", "materiales_construccion"]
    },
    {
        "nombre": "Holcim Argentina",
        "rubro": "Cementera / Construcción",
        "categoria": "construccion",
        "contacto": "comunicacion-arg@holcim.com",
        "telefono": "0800-444-4652",
        "web": "https://www.holcim.com.ar",
        "notas": "Dona cemento, hormigón y materiales para proyectos comunitarios. Fundación Holcim apoya construcción sustentable.",
        "provincia": "Córdoba",
        "tipo_donacion": ["cemento", "hormigon", "materiales_construccion"]
    },
    {
        "nombre": "Cerámica San Lorenzo",
        "rubro": "Materiales de Construcción",
        "categoria": "construccion",
        "contacto": "info@ceramicasanlorenzo.com",
        "telefono": "0800-888-7267",
        "web": "https://www.ceramicasanlorenzo.com.ar",
        "notas": "Fabrica cerámicos, pisos, revestimientos y sanitarios. Dona materiales para baños y cocinas comunitarias.",
        "provincia": "Buenos Aires",
        "tipo_donacion": ["ceramicos", "sanitarios", "revestimientos"]
    },
    {
        "nombre": "Ferrum",
        "rubro": "Sanitarios y Grifería",
        "categoria": "construccion",
        "contacto": "atencionclientes@ferrum.com",
        "telefono": "0800-333-3778",
        "web": "https://www.ferrum.com",
        "notas": "Líder en sanitarios, grifería y muebles de baño en Argentina. Evalúa donaciones de artefactos sanitarios para proyectos sociales.",
        "provincia": "Buenos Aires",
        "tipo_donacion": ["sanitarios", "griferia", "muebles_banio"]
    },
    {
        "nombre": "Roca Argentina",
        "rubro": "Sanitarios y Baños",
        "categoria": "construccion",
        "contacto": "info.ar@roca.net",
        "telefono": "011-5272-4100",
        "web": "https://www.roca.com.ar",
        "notas": "Multinacional de productos para baño. Programa Roca Solidaria evalúa donaciones de inodoros, lavatorios y accesorios.",
        "provincia": "Buenos Aires",
        "tipo_donacion": ["sanitarios", "inodoros", "lavatorios"]
    },
    {
        "nombre": "Easy / Cencosud",
        "rubro": "Materiales y Construcción",
        "categoria": "construccion",
        "contacto": "rse@cencosud.com.ar",
        "telefono": "0810-999-3279",
        "web": "https://www.easy.com.ar",
        "notas": "Cadena de materiales de construcción. A través de Cencosud RSE dona materiales, pintura y herramientas para proyectos comunitarios.",
        "provincia": "Nacional",
        "tipo_donacion": ["materiales_construccion", "herramientas", "pintura"]
    },
    {
        "nombre": "Sodimac",
        "rubro": "Materiales y Construcción",
        "categoria": "construccion",
        "contacto": "rse@sodimac.com.ar",
        "telefono": "0810-444-7634",
        "web": "https://www.sodimac.com.ar",
        "notas": "Cadena de materiales. Programa Hazlo con Nosotros apoya proyectos comunitarios con donación de materiales de construcción y ferretería.",
        "provincia": "Nacional",
        "tipo_donacion": ["materiales_construccion", "herramientas", "ferreteria"]
    },
    {
        "nombre": "Globant",
        "rubro": "Tecnología / Software",
        "categoria": "tecnologia",
        "contacto": "sustentabilidad@globant.com",
        "telefono": "011-4109-1700",
        "web": "https://www.globant.com",
        "notas": "Empresa argentina de tecnología. Programa Be Kind dona computadoras, equipamiento tecnológico y financia cursos de programación.",
        "provincia": "Buenos Aires",
        "tipo_donacion": ["computadoras", "cursos_tecnologia", "software"]
    },
    {
        "nombre": "Mercado Libre",
        "rubro": "Tecnología / E-commerce",
        "categoria": "tecnologia",
        "contacto": "sustentabilidad@mercadolibre.com",
        "telefono": "011-4640-8000",
        "web": "https://www.mercadolibre.com.ar",
        "notas": "A través de Mercado Libre Solidario dona equipamiento tecnológico, tablets y financia proyectos educativos tecnológicos.",
        "provincia": "Buenos Aires",
        "tipo_donacion": ["computadoras", "tablets", "proyectos_educativos"]
    },
    {
        "nombre": "Telecom Argentina",
        "rubro": "Telecomunicaciones",
        "categoria": "tecnologia",
        "contacto": "rse@telecom.com.ar",
        "telefono": "0800-555-0000",
        "web": "https://www.telecom.com.ar",
        "notas": "Fundación Telecom dona equipamiento de conectividad, routers, módems. Programa Digit@lers da cursos de tecnología gratuitos.",
        "provincia": "Buenos Aires",
        "tipo_donacion": ["conectividad", "equipamiento_red", "cursos_tecnologia"]
    },
    {
        "nombre": "Fundación Equidad",
        "rubro": "Tecnología / Reciclaje IT",
        "categoria": "tecnologia",
        "contacto": "donaciones@fundacionequidad.org.ar",
        "telefono": "011-4581-0825",
        "web": "https://www.fundacionequidad.org.ar",
        "notas": "Recicla y reacondiciona computadoras donadas por empresas para entregarlas a organizaciones sociales y comedores.",
        "provincia": "Buenos Aires",
        "tipo_donacion": ["computadoras_reacondicionadas", "notebooks", "talleres"]
    },
    {
        "nombre": "Nubimetrics",
        "rubro": "Tecnología / Data",
        "categoria": "tecnologia",
        "contacto": "impacto@nubimetrics.com",
        "telefono": "",
        "web": "https://www.nubimetrics.com",
        "notas": "Startup argentina. Tiene programa de donación de equipos informáticos y apoya capacitaciones tecnológicas comunitarias.",
        "provincia": "Jujuy",
        "tipo_donacion": ["computadoras", "capacitaciones_tecnologicas"]
    },
    {
        "nombre": "Fundación Santander",
        "rubro": "Banca / Educación",
        "categoria": "educacion",
        "contacto": "fundacionsantander@santander.com.ar",
        "telefono": "011-4341-1000",
        "web": "https://www.santander.com.ar",
        "notas": "Dona becas, útiles escolares, libros y materiales educativos. Apoya proyectos de educación comunitaria.",
        "provincia": "Buenos Aires",
        "tipo_donacion": ["libros", "utiles", "becas", "materiales_educativos"]
    },
    {
        "nombre": "Fundación La Nación",
        "rubro": "Medios / Educación",
        "categoria": "educacion",
        "contacto": "fundacion@lanacion.com.ar",
        "telefono": "011-4319-1900",
        "web": "https://www.fundacionlanacion.org.ar",
        "notas": "Dona libros, cuadernos y materiales de lectura. Programa +Educación apoya proyectos de alfabetización y formación.",
        "provincia": "Buenos Aires",
        "tipo_donacion": ["libros", "cuadernos", "material_lectura"]
    },
    {
        "nombre": "Fundación Leer",
        "rubro": "Educación / Lectura",
        "categoria": "educacion",
        "contacto": "info@leer.org.ar",
        "telefono": "011-4777-1111",
        "web": "https://www.leer.org.ar",
        "notas": "Dona libros infantiles y juveniles, bibliotecas completas para organizaciones sociales y merenderos. Capacita en alfabetización.",
        "provincia": "Buenos Aires",
        "tipo_donacion": ["libros", "bibliotecas", "capacitacion_alfabetizacion"]
    },
    {
        "nombre": "Carrefour Argentina",
        "rubro": "Supermercados",
        "categoria": "alimentacion",
        "contacto": "fundacion@carrefour.com.ar",
        "telefono": "0800-444-8484",
        "web": "https://www.carrefour.com.ar",
        "notas": "Fundación Carrefour dona alimentos no perecederos, mercadería próxima a vencer y útiles escolares. Apoya merenderos y comedores.",
        "provincia": "Nacional",
        "tipo_donacion": ["alimentos", "utiles", "mercaderia"]
    },
    {
        "nombre": "Coca-Cola Argentina",
        "rubro": "Bebidas / Alimentos",
        "categoria": "alimentacion",
        "contacto": "sustentabilidad@coca-cola.com.ar",
        "telefono": "011-4328-8000",
        "web": "https://www.coca-coladeargentina.com.ar",
        "notas": "A través de Fundación Coca-Cola apoya comedores comunitarios con bebidas, alimentos y equipamiento para cocinas.",
        "provincia": "Buenos Aires",
        "tipo_donacion": ["bebidas", "alimentos", "equipamiento_cocina"]
    },
    {
        "nombre": "Mastellone Hnos. (La Serenísima)",
        "rubro": "Lácteos / Alimentos",
        "categoria": "alimentacion",
        "contacto": "rse@mastellone.com.ar",
        "telefono": "0800-444-5737",
        "web": "https://www.mastellone.com.ar",
        "notas": "Principal empresa láctea argentina. Dona leche, yogures y productos lácteos a comedores y merenderos comunitarios.",
        "provincia": "Buenos Aires",
        "tipo_donacion": ["lacteos", "leche", "alimentos"]
    },
    {
        "nombre": "Molinos Río de la Plata",
        "rubro": "Alimentos",
        "categoria": "alimentacion",
        "contacto": "rse@molinos.com.ar",
        "telefono": "0800-555-4321",
        "web": "https://www.molinos.com.ar",
        "notas": "Dona fideos, harinas, arroz, aceite y alimentos secos a comedores. Tiene programa permanente de donación a organizaciones sociales.",
        "provincia": "Buenos Aires",
        "tipo_donacion": ["alimentos_secos", "fideos", "arroz", "aceite"]
    },
    {
        "nombre": "Banco de Alimentos de Buenos Aires",
        "rubro": "Organización Social / Alimentos",
        "categoria": "alimentacion",
        "contacto": "info@bancodealimentos.org.ar",
        "telefono": "011-4724-0017",
        "web": "https://www.bancodealimentos.org.ar",
        "notas": "Recibe donaciones de alimentos de empresas y los distribuye a comedores y merenderos. IEA puede registrarse como entidad receptora.",
        "provincia": "Buenos Aires",
        "tipo_donacion": ["alimentos", "mercaderia", "distribucion"]
    },
    {
        "nombre": "Grupo Sancor Seguros",
        "rubro": "Seguros / RSE",
        "categoria": "general",
        "contacto": "fundacion@gds.com.ar",
        "telefono": "0800-555-7262",
        "web": "https://www.gds.com.ar",
        "notas": "Fundación Grupo Sancor Seguros financia proyectos comunitarios, dona mobiliario y apoya infraestructura de organizaciones sociales.",
        "provincia": "Santa Fe",
        "tipo_donacion": ["mobiliario", "financiamiento", "infraestructura"]
    },
    {
        "nombre": "YPF",
        "rubro": "Energía / Petróleo",
        "categoria": "general",
        "contacto": "fundacionypf@ypf.com",
        "telefono": "0800-122-2973",
        "web": "https://www.ypf.com",
        "notas": "Fundación YPF apoya proyectos educativos, comunitarios y de infraestructura. Dona materiales y financia obras en comunidades.",
        "provincia": "Nacional",
        "tipo_donacion": ["financiamiento", "materiales", "proyectos_educativos"]
    },
    {
        "nombre": "Fundación Banco Macro",
        "rubro": "Banca",
        "categoria": "general",
        "contacto": "fundacion@macro.com.ar",
        "telefono": "0800-555-6227",
        "web": "https://www.macro.com.ar",
        "notas": "Apoya proyectos de salud, educación e infraestructura en el interior del país. Evalúa donaciones directas a organizaciones sociales.",
        "provincia": "Nacional",
        "tipo_donacion": ["financiamiento", "materiales_educativos", "infraestructura"]
    },
    {
        "nombre": "Fundación IRSA",
        "rubro": "Inmobiliaria / Construcción",
        "categoria": "general",
        "contacto": "fundacion@irsa.com.ar",
        "telefono": "011-4323-8000",
        "web": "https://www.irsa.com.ar",
        "notas": "Dona terrenos, materiales de construcción y financia obras de infraestructura para proyectos sociales y comunitarios.",
        "provincia": "Buenos Aires",
        "tipo_donacion": ["materiales_construccion", "terrenos", "infraestructura"]
    },
    {
        "nombre": "Fundación Andreani",
        "rubro": "Logística / Transporte",
        "categoria": "general",
        "contacto": "fundacion@andreani.com",
        "telefono": "0810-122-1111",
        "web": "https://www.andreani.com",
        "notas": "Dona servicios de logística, transporte de donaciones y envío de materiales. Apoya la logística de organizaciones sociales sin costo.",
        "provincia": "Nacional",
        "tipo_donacion": ["logistica", "transporte", "envios"]
    },
    {
        "nombre": "Cámara Argentina de la Construcción",
        "rubro": "Construcción / Cámara Empresarial",
        "categoria": "construccion",
        "contacto": "camarco@camarco.org.ar",
        "telefono": "011-4361-8000",
        "web": "https://www.camarco.org.ar",
        "notas": "Agrupa empresas constructoras. Puede conectar con empresas dispuestas a donar materiales. Programa de RSE sectorial activo.",
        "provincia": "Buenos Aires",
        "tipo_donacion": ["contactos_empresas", "materiales_construccion"]
    },
    {
        "nombre": "DonarTech",
        "rubro": "Tecnología / Donaciones IT",
        "categoria": "tecnologia",
        "contacto": "info@donartech.org.ar",
        "telefono": "",
        "web": "https://www.donartech.org.ar",
        "notas": "Plataforma que conecta donantes de equipamiento tecnológico con organizaciones sociales. Registra a IEA como beneficiaria para recibir computadoras.",
        "provincia": "Nacional",
        "tipo_donacion": ["computadoras", "impresoras", "equipamiento_it"]
    },
    {
        "nombre": "Fundación Garrahan",
        "rubro": "Reciclaje Solidario",
        "categoria": "general",
        "contacto": "info@vapor3.com.ar",
        "telefono": "011-4941-1333",
        "web": "https://www.fundaciongarrahan.org.ar",
        "notas": "Recibe tapitas, papel y llaves para reciclar y financia proyectos. También acepta donaciones de materiales que redistribuye. Pueden articular con IEA.",
        "provincia": "Buenos Aires",
        "tipo_donacion": ["reciclaje", "materiales_reciclables", "financiamiento"]
    },
    {
        "nombre": "Fundación Huésped",
        "rubro": "Salud / Desarrollo Social",
        "categoria": "general",
        "contacto": "donaciones@huesped.org.ar",
        "telefono": "011-4981-7777",
        "web": "https://www.huesped.org.ar",
        "notas": "Aunque enfocada en salud, articula donaciones de empresas para proyectos comunitarios y puede asesorar en gestión de donaciones.",
        "provincia": "Buenos Aires",
        "tipo_donacion": ["asesoramiento", "articulacion", "donaciones"]
    },
    {
        "nombre": "Danone Argentina",
        "rubro": "Alimentos / Lácteos",
        "categoria": "alimentacion",
        "contacto": "comunicacion.ar@danone.com",
        "telefono": "011-5777-5000",
        "web": "https://www.danone.com.ar",
        "notas": "Dona yogures, aguas y productos lácteos. Programa 'Un vaso de leche' apoya merenderos con donaciones regulares de alimentos.",
        "provincia": "Buenos Aires",
        "tipo_donacion": ["lacteos", "agua", "alimentos"]
    },
    {
        "nombre": "Grupo Clarín",
        "rubro": "Medios / Papel",
        "categoria": "educacion",
        "contacto": "rse@grupoclarin.com",
        "telefono": "011-4309-1000",
        "web": "https://www.grupoclarin.com",
        "notas": "A través de Fundación Noble dona papel, libros y materiales de lectura. Apoya proyectos educativos y de alfabetización comunitaria.",
        "provincia": "Buenos Aires",
        "tipo_donacion": ["papel", "libros", "material_lectura"]
    },
    {
        "nombre": "Ternium Argentina",
        "rubro": "Siderurgia / Acero",
        "categoria": "construccion",
        "contacto": "comunidad@ternium.com.ar",
        "telefono": "011-4018-1000",
        "web": "https://www.ternium.com.ar",
        "notas": "Dona acero, chapas y materiales para construcción de infraestructura comunitaria. Programa de desarrollo comunitario activo.",
        "provincia": "Buenos Aires",
        "tipo_donacion": ["acero", "chapas", "materiales_construccion"]
    },
    {
        "nombre": "Acindar (Grupo ArcelorMittal)",
        "rubro": "Siderurgia / Acero",
        "categoria": "construccion",
        "contacto": "rse@acindar.com.ar",
        "telefono": "011-4719-8500",
        "web": "https://www.acindar.com.ar",
        "notas": "Dona alambres, mallas, clavos y materiales de acero para construcción. Apoya infraestructura de organizaciones sociales.",
        "provincia": "Santa Fe",
        "tipo_donacion": ["alambres", "mallas", "clavos", "acero"]
    },
    {
        "nombre": "Fundación del Viso (Walmart Argentina)",
        "rubro": "Supermercados / RSE",
        "categoria": "alimentacion",
        "contacto": "fundaciondelviso@walmart.com",
        "telefono": "0800-444-9256",
        "web": "https://www.walmart.com.ar",
        "notas": "Dona alimentos, mercadería y productos de limpieza. Apoya comedores con donaciones periódicas de productos no perecederos.",
        "provincia": "Nacional",
        "tipo_donacion": ["alimentos", "mercaderia", "limpieza"]
    },
    {
        "nombre": "Fundación Itaú",
        "rubro": "Banca / Cultura",
        "categoria": "educacion",
        "contacto": "fundacion@itau.com.ar",
        "telefono": "0800-345-4828",
        "web": "https://www.itau.com.ar",
        "notas": "Dona libros, apoya bibliotecas comunitarias y financia proyectos educativos y culturales para organizaciones sociales.",
        "provincia": "Buenos Aires",
        "tipo_donacion": ["libros", "bibliotecas", "financiamiento_cultural"]
    },
    {
        "nombre": "Dánica",
        "rubro": "Alimentos",
        "categoria": "alimentacion",
        "contacto": "info@danica.com.ar",
        "telefono": "0341-426-9000",
        "web": "https://www.danica.com.ar",
        "notas": "Dona margarina, aceites y grasas vegetales a comedores comunitarios. Tiene programa de RSE para apoyo alimentario.",
        "provincia": "Santa Fe",
        "tipo_donacion": ["alimentos", "aceites", "margarina"]
    },
]
